name: Lint CSS

on: [pull_request, push]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Lint CSS
        run: npm run lint
